name = "Words Royale"
tags = ["Vue.js", "Express.js", "TypeScript", "SurrealDB", "GitHub Actions"]
dates = [1979-05-27T07:32:00-08:00, 1979-05-27T07:32:00-08:00]
inProd = true
status = "paused"

[description]
fr = """\
    Création de petites plaques en plexi contenant des QR codes uniques, \
    distribuées dans le cadre d'un concert de musique ; création d'une application web associée.\
    """
en = """\
    Creating small plexiglass plates containing unique QR codes distributed during a music concert, \
    developing an associated web application.\
    """

[[links]]
url = "https://29entertainment.fr/"
icon = "website"

    [links.text]
    fr = "Voir le site"
    en = "View the website"
